name: Lint Checks

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ master ]


jobs:
  lint:
    runs-on: ubuntu-latest
    container: cirrusci/flutter:beta
    strategy:
       fail-fast: false
       matrix:
         folder: [ ui, logic ]
    steps:
    - uses: actions/checkout@v2

    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-pub-deps
      with:
        path: ~/.pub-cache/hosted/
        key: ${{ env.cache-name }}-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          ${{ env.cache-name }}
    
    - name: Inject .env
      run: printf "%s" "$TESTS_DOTENV" > "logic/test/.env"

    - run: flutter pub get
      working-directory: ${{ matrix.folder }}

    - name: Check are there any warnings/infos/errors
      run: flutter --suppress-analytics analyze --no-pub
      working-directory: ${{ matrix.folder }}
      
  format:
    runs-on: ubuntu-latest
    container: cirrusci/flutter:beta
    steps:
    - uses: actions/checkout@v2

    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-pub-deps
      with:
        path: ~/.pub-cache/hosted/
        key: ${{ env.cache-name }}-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          ${{ env.cache-name }}

    - name: Check is code formatted well
      run: flutter --suppress-analytics format --show changed  --set-exit-if-changed . -o none --summary none